POST http://localhost:5050/room/create HTTP/1.1
Content-Type: application/json

{
    "nameRoom": "Armeria",
    "english": true,
    "firePrevention": true,
    "firstAid": false,
    "info": "Stai attento che i visitatori non facciano video.",
    "cover": "https://upload.wikimedia.org/wikipedia/commons/b/bf/6680_-_Milano%2C_Castello_sforzesco_-_Armeria_-_Armatura_da_fante%2C_sec._XVI_-_Foto_Giovanni_Dall%27Orto_-_14-Feb-2008.jpg"
}

####
POST http://localhost:5050/day/create HTTP/1.1
Content-Type: application/json

{
    "singleDay": "14 marzo 2023"
}

####
GET http://localhost:5050/day HTTP/1.1

####
GET http://localhost:5050/rooms HTTP/1.1

####
POST http://localhost:5050/workshift/create HTTP/1.1
Content-Type: application/json

{
    "day": "653ea4471534047440eeb065",
    "room": "stanza",
    "keeper": "ciao"
}

####
POST http://localhost:5050/keeper/create HTTP/1.1
Content-Type: application/json

{
    "nameKeeper": "Veronica",
    "surnameKeeper": "Vassallo",
    "email": "marica@gmail.com",
    "password":"veronica",
    "referent": false,
    "english": false,
    "firePrevention": true,
    "firstAid": true,
    "avatar": "https://as2.ftcdn.net/v2/jpg/02/79/66/93/1000_F_279669366_Lk12QalYQKMczLEa4ySjhaLtx1M2u7e6.jpg"
}

####
GET http://localhost:5050/day/2023-10-31 HTTP/1.1

####
GET http://localhost:5050/workshift/65412d4ce12fe2e38b2bc328 HTTP/1.1

####
GET http://localhost:5050/keepers/653e87433f6835f7eb92e481/65441b3a1bf46f4741b5fe6d HTTP/1.1

####
PATCH http://localhost:5050/workshift/6543e04bc7a8bdcaa95c8bdf/keeper HTTP/1.1
Content-Type: application/json

{
    "keeper": "65429e34a5be70e496d947c3"
}

####
PATCH http://localhost:5050/workshift/6543e04bc7a8bdcaa95c8bdf/keeper/remove HTTP/1.1

####
POST http://localhost:5050/login HTTP/1.1
Content-Type: application/json

{
    "email": "marica@gmail.com",
    "password": "maricapassword"
}

####
GET http://localhost:5050/workshift/specific/6547eaafb34900dbea05d7b5 HTTP/1.1

####
DELETE http://localhost:5050/day/delete/654930ae904aa7a5df2462e6 HTTP/1.1

####
GET http://localhost:5050/room/653c0aac4d1d3a8652e49a8f HTTP/1.1
